INSERT INTO USERS (ID, USER_NAME, PASSWORD, ROLE) VALUES
  (1, 'user', 'password', 'ROLE_ADMIN');

  INSERT INTO POSTS(CONTENT, TITLE,USER_ID, CREATED) VALUES
  ('From Shire' , 'Frodo',1, NOW());

  INSERT INTO POSTS(CONTENT, TITLE,USER_ID, CREATED) VALUES
  ('From Shire' , 'Kira',1, NOW());

  INSERT INTO POSTS(CONTENT, TITLE,USER_ID, CREATED) VALUES
  ('From Shire' , 'Mila',1, NOW());

  INSERT INTO POSTS(CONTENT, TITLE,USER_ID, CREATED) VALUES
  ('From Shire' , 'Pipin',1, NOW());

  INSERT INTO POSTS(CONTENT, TITLE,USER_ID, CREATED) VALUES
  ('From Shire' , 'Gendelf',1, NOW());

  INSERT INTO POSTS(CONTENT, TITLE,USER_ID, CREATED) VALUES
  ('From Shire' , 'Auvin',1, NOW());

  INSERT INTO POSTS(CONTENT, TITLE,USER_ID, CREATED) VALUES
  ('From Shire' , 'Kamila',1, NOW());

  INSERT INTO POSTS(CONTENT, TITLE,USER_ID, CREATED) VALUES
  ('From Shire' , 'Some',1, NOW());

  INSERT INTO COMMENTS(CONTENT,POST_ID, USER_ID) VALUES
  ('First Comment', 1, 1);

